version: "3.7"
services:
    ci:
        build: 
            context: .
            target: builder
    app:
        build:
            context: .
            target: package
    deploy:
        build:
            context: .
            target: deploy
