steps:
  - label: ":docker: Build"
    plugins:
      - docker-login#v2.0.1:
          username: $DOCKER_LOGIN_USERNAME
      - docker-compose#v3.7.0:
          build: ci
          image-repository: caseymichael/peters
  
  - wait

  - label: ":buildkite: Clubhouse Badge"
    if: build.branch != "production"
    plugins:
      - caseymichael/clubhouse-buildkite-status-badge#v0.0.5:
          CLUBHOUSE_API_TOKEN: "$CLUBHOUSE_API_TOKEN"
          BUILDKITE_BRANCH: "$BUILDKITE_BRANCH"
          REPOSITORY_NAME: "crowdsourceradioserver"
          BUILDKITE_PIPELINE_URL: "https://buildkite.com/peters"
          BUILDKITE_PIPELINE_BADGE_URL: "https://badge.buildkite.com/9650d50ed3ffb1074a6e44e09e653a27a8d265565074f97415.svg"

  - label: ":java: Lint"
    command: .scripts/lint.sh
    plugins:
      - docker-compose#v3.7.0:
          run: ci

  - label: ":junit: Test"
    command: .scripts/test.sh
    plugins:
      - docker-compose#v3.7.0:
          run: ci

  # - wait

  - label: ":docker: Push"
    plugins:
      - docker-compose#v3.7.0:
          build: app
          image-name: crowdsourceradioserver-$BUILDKITE_BUILD_NUMBER
          image-repository: caseymichael/peters
  
  - wait

  - label: ":kubernetes: Deploy"
    command: .scripts/deploy.sh
    plugins:
      - docker-compose#v3.7.0:
          run: ci