steps:
  - label: ":docker: Build"
    plugins:
      - docker-compose#v3.7.0:
          build: app
  
  - wait

  - label: ":junit: Test"
    command: .scripts/test.sh
    plugins:
      - docker-compose#v3.7.0:
          run: app
