steps:
  label: ":docker: Build"
  - plugins:
      - docker-compose#v3.7.0:
          build: app
  
  - wait

  - command: .scripts/test.sh
    label: ":junit: Test"
    plugins:
      - docker-compose#v3.7.0:
          run: app
